/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:c3a93313-6ea3-4bfd-84d8-7b8f63b8701c',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_CG0F7lv9S',
  aws_user_pools_web_client_id: '7cs53cd2srgqqo4j4r5fspjp60',
  oauth: {
    domain: 'zadacha53eecd31-53eecd31-dev.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: 'exp://127.0.0.1:19000/--/',
    redirectSignOut: 'exp://127.0.0.1:19000/--/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_login_mechanisms: ['EMAIL'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ['EMAIL']
}

export default awsmobile
